#!/bin/bash
echo "<< -----------  Run UDF << AS  Set >> Tests ----------------- >> "


export UNS="test"
export USET="set"
export UKEY="Key_ABC"
export SETBIN="SetBin"
export UFILE="AsSetStrawman"

# Use this ONLY if we need to register the UDF
# ascli udf-put $UFILE

echo ">> CREATE (Simple Put: key $UKEY) for use with UDF"
ascli put $UNS $USET $UKEY '{"Test Bin": "Set Test ONE"}'

echo ">> Check CREATE (key $UKEY) with get"
ascli get $UNS $USET $UKEY

echo ">> Call UDF Set Create: asSetCreate $UNS $USET $SETBIN 4"
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetCreate $UNS $USET $SETBIN 0

echo ">> Check CREATE (key $UKEY) with get"
ascli get $UNS $USET $UKEY

echo ">> Call UDF Set Insert: asSetInsert $SETBIN 199000111 - 199000444"
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000111
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000212
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000313
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000414
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000515
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000616
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000717
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000818
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199000919
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199001010
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199001111
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199001212
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199001313
ascli udf-record-apply $UNS $USET $UKEY $UFILE asSetInsert $SETBIN 199001414

echo ">> Check CREATE (key $UKEY) with get"
ascli get $UNS $USET $UKEY

# ########################################################################
echo ">>>>  EXIT <<<<<"
exit 0
# ########################################################################

echo ">> Call UDF Stack Peek(): Key($UKEY) $UFILE stackPeek"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPeek 0 0

echo ">> Call UDF Stack Push: ==> $UFILE stackPush '[21,22,23,24]'"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush '[21,22,23,24]' 
echo ">> Call UDF Stack Push: ==> $UFILE stackPush '[31,32,33,34]'"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush '[31,32,33,34]'

# echo ">> Check PROGRESS with GET!!!"
# ascli get $UNS $USET $UKEY

# echo ">> Call UDF StackPeek(): Key($UKEY) $UFILE stackPeek"
# ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPeek 0 0

# echo ">> Check PROGRESS with GET!!!"
# ascli get $UNS $USET $UKEY

# echo ">> Call UDF Stack Push: ==> $UFILE stackPush '[41,42,43,44]'"
# ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush '[41,42,43,44]'

# echo ">> Call UDF Stack Push: ==> $UFILE stackPush '[51,52,53,54]'"
# ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush '[51,52,53,54]'

# echo ">> Call UDF StackPeek(): Key($UKEY) $UFILE stackPeek"
# ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPeek 0 0

# echo ">> Check PROGRESS with GET!!!"
# ascli get $UNS $USET $UKEY

echo ">> Call UDF Stack >> Populate()<<: Key($UKEY) $UFILE stackPopulate"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPopulate 20

echo ">> Check PROGRESS with GET!!!"
ascli get $UNS $USET $UKEY

echo ">> Call UDF StackPeek(): Key($UKEY) $UFILE stackPeek"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPeek 0 0

# echo ">> Check PROGRESS with GET!!!"
# ascli get $UNS $USET $UKEY


# ########################################################################
echo ">>>>  EXIT <<<<<"
exit 0
# ########################################################################
