.PHONY: default
default: all

%:
	$(MAKE) -C example1 $@
	$(MAKE) -C example2 $@
	$(MAKE) -C example3 $@
	$(MAKE) -C example4 $@
	$(MAKE) -C example5 $@
	$(MAKE) -C example6 $@
	$(MAKE) -C operate_example $@
