.PHONY: default
default: all

%:
	$(MAKE) -C cpp_example $@
	$(MAKE) -C example $@
	$(MAKE) -C exists_example $@
	# $(MAKE) -C ldt_examples $@
	$(MAKE) -C udf_examples $@
	# $(MAKE) -C web_example $@
