name: aerospike-client-c

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-c:centos-6
      - docker.qe.aerospike.com/build/aerospike-client-c:centos-7
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-7
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-8
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-9
      - docker.qe.aerospike.com/build/aerospike-client-c:ubuntu-12.04
      - docker.qe.aerospike.com/build/aerospike-client-c:ubuntu-14.04
      - docker.qe.aerospike.com/build/aerospike-client-c:ubuntu-16.04

build:
  - name: default
    script:
      - make package
    artifact:
      - target/packages/*
