name: aerospike-client-c

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-c:centos-7
      - docker.qe.aerospike.com/build/aerospike-client-c:rhel-8
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-9
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-10
      - docker.qe.aerospike.com/build/aerospike-client-c:debian-11
      - docker.qe.aerospike.com/build/aerospike-client-c:ubuntu-18.04
      - docker.qe.aerospike.com/build/aerospike-client-c:ubuntu-20.04

build:
  - name: default
    script:
      - make package
    artifact:
      - target/packages/*
