#!/bin/bash -e
ver=4.24
dir=libev-$ver
fn=$dir.tar.gz
url=http://dist.schmorp.de/libev/Attic/$fn

rm -rf $fn $dir

echo Download $url
wget $url

echo Extract $fn 
tar xf $fn

echo Make $dir
cd $dir
./configure -q
make CFLAGS=-w
sudo make install

echo Remove source $fn $dir
cd ..
rm -rf $fn $dir
