HEADERS = ev2citrusleaf.h ev2citrusleaf-internal.h cl_cluster.h 
SOURCES = ev2citrusleaf.c cl_info.c cl_cluster.c cl_lookup.c cl_partition.c cl_batch.c
CF_SOURCES = cf_alloc.c cf_average.c cf_digest.c cf_hist.c cf_hooks.c cf_ll.c cf_log.c cf_proto.c cf_queue.c cf_service.c cf_shash.c cf_socket.c cf_vector.c version.c
