#!/bin/bash
# LSO Unit Tests
# Test One - Raj's basic CREC Unit Teste
ascli udf-record-apply test set 10 LsoStickman mediumStackCreate
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 1
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 2
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 3
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 4
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 5
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 5
ascli udf-record-apply test set 10 LsoStickman mediumStackPush 6
ascli udf-record-apply test set 10 LsoStickman mediumStackPeek 10

