#!/bin/bash
echo "<< -----------  Run Basic AS Large Stack Object Test -------------- >> "
echo "<< -----------  <<<<    LSO Test 1            >>>>>> -------------- >> "

export UNS="test"
export USET="set"
export UKEY="abc"
export UFILE="LSTACK"
# export UFILE="LsoSuperMan"
# export UFILE="LsoStoneman"
export UCHUNK=2000

export UNS="test"
export USET="set"
# This script exercises the Aerospike LSO Functions
#
export UKEY="LSO_ABC"
export LSOBIN="LsoBin"
export FUN_CR8="lstack_create"
export FUN_INS="lstack_push"
export FUN_INSWU="lstack_push_with_create"
export FUN_SRCH="lstack_peek"
export FUN_SRCHWU="lstack_peek_with_filter"
export FUN_CONFIG="lstack_config"
export FUN_SIZE="lstack_size"
#############################
## Stack Create Parameters ##
#############################
# Configure the Server to be in "debug mode", which is to use very small sizes
# and exercise the warm and cold list structures.
export CREATE_ARGLIST='{"Package":"DebugModeList"}'

echo ">> Call UDF $FUN_CR8 : $LSOBIN $CREATE_ARGLIST << "
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_CR8  $LSOBIN $CREATE_ARGLIST

echo ">>>>> Multiple lstack_push() Calls <<<<"
echo ">>>>> lstack_push(): ==> $UFILE $FUN_INS $LSOBIN '[11,12,13,14]'"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[11,12,13,14]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[21,22,23,24]' 
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[31,32,33,34]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[41,42,43,44]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[51,52,53,54]'
echo ">>>>>>>>>>> Call lstack_push(): 15 more tuples <<<<<<<<<<<<<<<<<<<<"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[61,62,63,64]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[71,72,73,74]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[81,82,83,84]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[91,92,93,94]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[101,102,103,104]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[111,112,113,114]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[121,122,123,124]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[131,132,133,134]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[141,142,143,144]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[151,152,153,154]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[161,162,163,164]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[171,172,173,174]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[181,182,183,184]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[191,192,193,194]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSOBIN '[201,202,203,204]'

echo ">> Call lstack_peek(): Key($UKEY) $UFILE $FUN_SRCH $LSOBIN 0"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_SRCH  $LSOBIN 0

echo ">> Call UDF StackPeek(): Key($UKEY) $UFILE $FUN_SRCH $LSOBIN 0"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_SRCH  $LSOBIN 0

echo ">> Verify Object with GET <<"
ascli get $UNS $USET $UKEY

echo "<< >> << >> REMOVE THE RECORD << >> << >> "
ascli remove $UNS $USET $UKEY

# ########################################################################
echo ">>>>  EXIT <<<<<"
exit 0
# ########################################################################
