#!/bin/bash
echo "<< -----------  <<<<  NEW LSO Test 2  >>>>>> -------------- >> "
echo "<< ----------  Exercise ALL LSTACK FUNCTIONS  -------------- >> "

export UNS="test"
export USET="set"
export UKEY="abc"
export UFILE="LSTACK"

export UNS="test"
export USET="set"
# This script exercises the Aerospike LSO Functions
#
export UKEY="LSO_ABC"
export LSLBIN="LsoListBin"
export LSBBIN="LsoBinaryBin"
export FUN_CR8="lstack_create"
export FUN_INS="lstack_push"
export FUN_INSWU="lstack_push_with_create"
export FUN_SRCH="lstack_peek"
export FUN_SRCHWU="lstack_peek_with_filter"
export FUN_CONFIG="lstack_config"
export FUN_SIZE="lstack_size"
#############################
## Stack Create Parameters ##
#############################
# Configure the Server to be in "debug mode", which is to use very small sizes
# and exercise the warm and cold list structures.
export CREATE_ARGLIST='{"Package":"DebugModeList"}'

echo ">> Call UDF $FUN_CR8 : $LSLBIN $CREATE_ARGLIST << "
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_CR8  $LSLBIN $CREATE_ARGLIST

echo ">>>>> Multiple Stack Push Calls <<<<"
echo ">> Call UDF Stack Push: ==> $UFILE $FUN_INS $LSLBIN '[11,12,13,14]'"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[11,12,13,14]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[21,22,23,24]' 
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[31,32,33,34]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[41,42,43,44]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[51,52,53,54]'
echo ">>>>>>>>>>> Call UDF Stack Push: 15 more tuples <<<<<<<<<<<<<<<<<<<<"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[61,62,63,64]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[71,72,73,74]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[81,82,83,84]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[91,92,93,94]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[101,102,103,104]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[111,112,113,114]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[121,122,123,124]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[131,132,133,134]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[141,142,143,144]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[151,152,153,154]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[161,162,163,164]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[171,172,173,174]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[181,182,183,184]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[191,192,193,194]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_INS $LSLBIN '[201,202,203,204]'

echo ">> Call UDF StackPeek(): Key($UKEY) $UFILE $FUN_SRCH $LSLBIN 0"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_SRCH  $LSLBIN 0

echo ">> Get Object Size <<"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_SIZE $LSLBIN

echo ">> Get the LSO Config <<"
ascli udf-record-apply $UNS $USET $UKEY $UFILE $FUN_CONFIG $LSLBIN

echo "<< >> << >> REMOVE THE RECORD << >> << >> "
ascli remove $UNS $USET $UKEY

# ########################################################################
echo ">>>>  EXIT <<<<<"
exit 0
# ########################################################################
