#!/bin/bash

export UNS="test"
export USET="set"
export UKEY="abc"
export UFILE="LsoStickman"
export UCHUNK=2000

export UNS="test"
export USET="set"
# This script exercises the Aerospike LSO Functions
#
export UKEY="LSO_ABC"
export LSOBIN="LsoBin"
export UFILE="LsoStickman"
export FUN_CR8="stackCreate"
export FUN_INS="stackPush"
export FUN_INSWU="stackPushWithUDF"
export FUN_SRCH="stackPeek"
export FUN_SRCHWU="stackPeekWithUDF"
# export ARGLIST='[$LSOBIN,$UNS,$USET,$UCHUNK,1]'
export ARGLIST='["LsoBin","test","set",2000,1]'

PARALLEL_POPULATION=1

URLID=1000
URLID_MOD=9
CREATED=1400000000
METH_A=50000
METH_B=7000000
STATUS=1

echo "For USERS( count = $NUM_USERS ) Perform ( count = 200 ) Pushes"

USERID=8000
NUM_USERS=50
U=0;
while [ $U -lt $NUM_USERS ]; do
  ascli udf-record-apply $UNS $USET $USERID $UFILE stackCreate $LSOBIN $ARGLIST >/dev/null

  NUM_PUSHES=50;
  I=0;
  while [ $I -lt $NUM_PUSHES ]; do
    TUPLE="[${URLID},${CREATED},${METH_A},${METH_B},${STATUS}]"
    echo ascli udf-record-apply $UNS $USET $USERID $UFILE stackPush $LSOBIN $TUPLE
    if [ $PARALLEL_POPULATION -eq 1 ]; then
      ascli udf-record-apply $UNS $USET $USERID $UFILE stackPush $LSOBIN $TUPLE >/dev/null & </dev/null
    else
      ascli udf-record-apply $UNS $USET $USERID $UFILE stackPush $LSOBIN $TUPLE >/dev/null
    fi
    I=$[${I}+1];
    if [ $[${I}%${URLID_MOD}] -eq 0 ]; then URLID=$[${URLID}+1]; fi
    CREATED=$[${CREATED}+1];
    METH_A=$[${METH_A}+1];
    METH_B=$[${METH_B}+1];
    STATUS=$[${STATUS}+1];
  done
  echo wait on 20
  wait
  echo "UDF StackPeek(): Key($USERID) 20 items"
  ascli udf-record-apply $UNS $USET $USERID $UFILE stackPeek $LSOBIN 20 

  USERID=$[${USERID}+1];
  U=$[${U}+1];
done
