#!/bin/bash

PARALLEL_POPULATION=0

URLID=1000
URLID_MOD=9
CREATED=1400000000
METH_A=50000
METH_B=7000000
STATUS=1

USERID=2000
NUM_USERS=100
U=0;
while [ $U -lt $NUM_USERS ]; do
  NUM_PUSHES=200;
  I=0;
  while [ $I -lt $NUM_PUSHES ]; do
    TUPLE="[${URLID},${CREATED},${METH_A},${METH_B},${STATUS}]"
    echo ascli udf-record-apply $UNS $USET $USERID $UFILE stackPush $LSOBIN $TUPLE
    I=$[${I}+1];
    if [ $[${I}%${URLID_MOD}] -eq 0 ]; then URLID=$[${URLID}+1]; fi
    CREATED=$[${CREATED}+1];
    METH_A=$[${METH_A}+1];
    METH_B=$[${METH_B}+1];
    STATUS=$[${STATUS}+1];
  done
  echo ascli udf-record-apply $UNS $USET $USERID $UFILE stackPeek $LSOBIN 0
  USERID=$[${USERID}+1];
  U=$[${U}+1];
done

