#!/bin/bash
echo "<< -----------  Run Basic AS Large Stack Object Test -------------- >> "
echo "<< -----------  <<<<    LSO Test 1            >>>>>> -------------- >> "

export UNS="test"
export USET="set"
export UKEY="abc"
export UFILE="LsoStoneman"
export UCHUNK=2000

export UNS="test"
export USET="set"
# This script exercises the Aerospike LSO Functions
#
export UKEY="LSO_ABC"
export LSOBIN="LsoBin"
export FUN_CR8="stackCreate"
export FUN_INS="stackPush"
export FUN_INSWU="stackPushWithUDF"
export FUN_SRCH="stackPeek"
export FUN_SRCHWU="stackPeekWithUDF"
#############################
## Stack Create Parameters ##
#############################
# PageMode can be "List" or "Binary"
# ByteEntrySize is needed for "Binary" mode.  Size of the packed item
# (e.g. StumbleUpon data is packed into an 18 byte item)
# HotListSize is a number -- the max size of the Hot List
# Realistic sizes are 50 to 200.  Try lower to exercise the system.
# HotListTransfer is a number -- the amount of the Hot List to age out.
# ==> It MUST be LESS than the HotListSize (it is usually half of HLS)
export CREATE_ARGLIST='{"PageMode":"List","HotListSize":120}'

echo ">> Call UDF Stack Create: $LSOBIN $CREATE_ARGLIST << "
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackCreate $LSOBIN $CREATE_ARGLIST

echo ">>>>> Multiple Stack Push Calls <<<<"
echo ">> Call UDF Stack Push: ==> $UFILE stackPush $LSOBIN '[11,12,13,14]'"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[11,12,13,14]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[21,22,23,24]' 
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[31,32,33,34]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[41,42,43,44]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[51,52,53,54]'
echo ">>>>>>>>>>> Call UDF Stack Push: 5 more tuples <<<<<<<<<<<<<<<<<<<<"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[61,62,63,64]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[71,72,73,74]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[81,82,83,84]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[91,92,93,94]'
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPush $LSOBIN '[101,102,103,104]'

echo ">> Call UDF StackPeek(): Key($UKEY) $UFILE stackPeek $LSOBIN 0"
ascli udf-record-apply $UNS $USET $UKEY $UFILE stackPeek  $LSOBIN 0

echo ">> Verify Object with GET <<"
ascli get $UNS $USET $UKEY

echo "<< >> << >> REMOVE THE RECORD << >> << >> "
ascli remove $UNS $USET $UKEY

# ########################################################################
echo ">>>>  EXIT <<<<<"
exit 0
# ########################################################################
