# Minimal single-node config for the ael-gui container's internal server.

service {
	run-as-daemon false
	proto-fd-max 1024

	work-directory /opt/aerospike/work
	cluster-name ael-gui
}

mod-lua {
	user-path /opt/aerospike/work/usr/udf/lua
	allow-unsafe-lua false
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		port 3002

		interval 150
		timeout 10
	}

	fabric {
		port 3001
	}

	admin {
		address any
		port 3003
	}
}

namespace test {
	replication-factor 1

	storage-engine memory {
		data-size 1G
	}
}
