#!/bin/bash
# Install all prequisites that are required by the Aerospike xcode project
# on MacOS.  This script only needs to be run once.

cd `dirname $0`

# Install MacOS prerequisites
brew install wget
brew install automake
brew install libtool
brew install openssl
brew install libyaml

# Must perform make to create liblua.a that is referenced in xcode project.
cd ..
git submodule update --init
make -C modules/lua CFLAGS="-Wall -O2 -std=c99 -DLUA_USE_MACOSX -fPIC -fno-stack-protector -fno-common -g" a

# Open C client workspace in xcode.
open xcode/client.xcworkspace
