.PHONY: default
default: all

%:
	$(MAKE) -C async_batch_get $@
	$(MAKE) -C async_delay_queue $@
	$(MAKE) -C async_get $@
	$(MAKE) -C async_query $@
	$(MAKE) -C async_scan $@
	$(MAKE) -C async_transaction $@
