#!/bin/bash
# Package libraries.

set -e

function PrintUsage {
  echo "Usage: $0 [-sign] lib|devel sync|libuv|libev|libevent <client dir> <stage dir> <target dir>"
  exit 1
}

if [ "$1" = "-sign" ]
then
  signPackage=$1
  shift
fi

if [ $# -ne 5 ]
then
  PrintUsage
fi

pkgType=$1
eventlib=$2
baseDir=$3
stageDir=$4
targetDir=$5

case $eventlib in
  sync)
    eventId=""
    eventName=""
    eventDesc=""
    ;;

  libev)
    eventId=".libev"
    eventName="-libev"
    eventDesc=" with libev"
    ;;

  libuv)
    eventId=".libuv"
    eventName="-libuv"
    eventDesc=" with libuv"
    ;;

  libevent)
    eventId=".libevent"
    eventName="-libevent"
    eventDesc=" with libevent"
    ;;

  *)
    echo Invalid eventlib $eventlib
    PrintUsage
    ;;
esac

case $pkgType in
  lib)
    idSuffix=""
    pkgSuffix=""
    ;;

  devel)
    idSuffix=".devel"
    pkgSuffix="-devel"
    ;;

  *)
    echo Invalid pkgType $pkgType
    PrintUsage
    ;;
esac

cd `dirname $0`

platform=`./platform`
rev=`./version`

# Create library package.
buildDir=$stageDir/BUILD

rm -rf $buildDir

function CreatePackage {
  topDir=$buildDir/$1
  optDir=$buildDir/$2
  trgName=$3

  mkdir -p $topDir/lib

  # Mode is left to whatever cp + the calling shell's umask produce.
  # Source files are 0644 / dirs 0755; with the default 0022 umask the staged
  # copies are already 0644/0755 (no group/other write to strip).  The spec
  # files use %defattr(-,root,root) so rpm packages whatever mode is on disk.

  ### DEBUG ###
  echo "=== package_type CreatePackage debug ==="
  echo "  pkgType=$pkgType  topDir=$topDir  trgName=$trgName"
  echo "  whoami: $(id)   umask: $(umask)"
  echo "  source dir ls -lan (target/$trgName):"
  ls -lan "$baseDir/target/$trgName/lib" 2>&1 | head -5
  ls -lan "$baseDir/target/$trgName/include/aerospike" 2>&1 | head -5
  ### END DEBUG ###

  if [ "$pkgType" = "devel" ]
  then
    cp    $baseDir/target/$trgName/lib/libaerospike.a $topDir/lib
    cp -r $baseDir/target/$trgName/include $topDir
  else
    cp    $baseDir/target/$trgName/lib/libaerospike.* $topDir/lib
    rm $topDir/lib/libaerospike.a
  fi

  ### DEBUG ###
  echo "  staged dir ls -lan ($topDir):"
  ls -lan "$topDir/lib" 2>&1 | head -5
  if [ -d "$topDir/include/aerospike" ]; then
    ls -lan "$topDir/include/aerospike" 2>&1 | head -5
    # Probe the exact failure: can we chmod a staged .h file?
    probe="$topDir/include/aerospike/as_error.h"
    if [ -f "$probe" ]; then
      echo "  chmod probe on staged .h:"
      stat -c '    pre : mode=%a uid=%u gid=%g name=%n' "$probe"
      if chmod 0644 "$probe" 2>&1; then
        echo "    chmod 0644 OK"
      else
        echo "    chmod 0644 FAILED ^^"
      fi
    fi
  fi
  echo "=== end package_type debug ==="
  ### END DEBUG ###
}

case ${platform:0:2} in

el|fc|am)
  arch=`uname -m`
  os=`uname -s`-$arch
  CreatePackage usr opt $os
  rpmrev=`echo $rev | sed 's/-/_/g'`
  sed -e "s/@EVENTNAME@/$eventName/g" -e "s/@EVENTDESC@/$eventDesc/g" -e "s/@VERSION@/$rpmrev/g" -e "s/@ARCH@/$arch/g" < rpm/client$pkgSuffix.spec > $stageDir/rpm.spec
  rpmbuild -bb -vv --noclean --define "dist .$platform" --define "_topdir $stageDir" --buildroot $buildDir $stageDir/rpm.spec
  mv $stageDir/RPMS/$arch/aerospike-client-c$eventName$pkgSuffix-$rpmrev*.rpm $targetDir
  rm $stageDir/rpm.spec
  ;;

de|ub)
  arch=`dpkg-architecture -qDEB_HOST_ARCH`
  os=`uname -s`-`uname -m`
  CreatePackage usr opt $os
  mkdir -p $buildDir/DEBIAN
  install -m 755 deb/postinst.client $buildDir/DEBIAN/postinst
  sed -e "s/@EVENTNAME@/$eventName/g" -e "s/@EVENTDESC@/$eventDesc/g" -e "s/@VERSION@/$rev/g" -e "s/@ARCH@/$arch/g" < deb/client$pkgSuffix.spec > $buildDir/DEBIAN/control
  fakeroot dpkg-deb --build $buildDir $targetDir/aerospike-client-c$eventName$pkgSuffix"_"$rev"-"$platform"_"$arch.deb
  ;;

ma)
  arch=`uname -m`
  os=`uname -s`-$arch
  CreatePackage usr/local usr/local $os
  if [ "$signPackage" = "-sign" ]
  then
    if [ "$pkgType" = "devel" ]
    then
      codesign --force --sign "Developer ID Application: Aerospike, Inc." $buildDir/usr/local/lib/libaerospike.a
    else
      codesign --force --sign "Developer ID Application: Aerospike, Inc." $buildDir/usr/local/lib/libaerospike.dylib
    fi
    pkgbuild --identifier com.aerospike.client.c$eventId$idSuffix.$rev --root $buildDir $targetDir/unsigned.pkg
    productsign --sign "Developer ID Installer: Aerospike, Inc." $targetDir/unsigned.pkg $targetDir/aerospike-client-c$eventName$pkgSuffix-$rev-$arch.pkg
    rm $targetDir/unsigned.pkg
  else
    pkgbuild --identifier com.aerospike.client.c$eventId$idSuffix.$rev --root $buildDir $targetDir/aerospike-client-c$eventName$pkgSuffix-$rev-$arch.pkg    
  fi
  ;;

*)
  echo Invalid platform $platform
  exit 1
  ;;

esac

rm -rf $buildDir
