#!/bin/bash
# Display current operating system.

rel=`uname`

if [ "$rel" = "Darwin" ]
then
  echo mac
  exit 0
fi

if [ "$rel" != "Linux" ]
then
  echo "Unknown platform"
  exit 1
fi

if [ -f /etc/redhat-release ]
then
  uname -r | awk -F. '{if (index($NF,"el") == 1 || index($NF,"fc") == 1) print $NF; else print $(NF-1);}'
  exit 0
elif [ -f /etc/issue ]
then
  os=`cat /etc/issue | awk '{print $1}'`

  if [ "$os" = "Debian" ]
  then
    ver=`cat /etc/issue | tr -d '\n' | awk '{print $3}' | awk -F'.' '{print $1}'`
    echo debian$ver
  elif [ "$os" = "Ubuntu" ]
  then
    ver=`cat /etc/issue | tr -d '\n' | awk '{print $2}' | awk -F'.' '{printf("%s.%s\n",$1,$2)}'`
    echo ubuntu$ver
  fi
  exit 0
fi

echo "Unknown platform"
exit 1    
