#!/bin/bash -e
# Set version in version.h and version.c.

if [ $# -lt 1 ]
then
	echo "Usage: $0 <version>"
	exit 1
fi

version=$1

cd `dirname $0`

# Write version.h
ver=`echo $version | awk -F. '{printf("%d%02d%02d%04dL\n", $1, $2, $3, $4)}'`
fn=../src/include/aerospike/version.h
tmp=/tmp/version.h

awk '{
	if ($2 == "AEROSPIKE_CLIENT_VERSION") {
    printf("#define AEROSPIKE_CLIENT_VERSION %s\n", "'$ver'");	
	}
  else {
  	print $0;
  }
}' < $fn > $tmp

mv $tmp $fn

# Write version.c
fn=../src/main/aerospike/version.c
tmp=/tmp/version.c

awk '{
	if ($3 == "aerospike_client_version") {
    printf("AS_EXTERN char* aerospike_client_version = \"%s\";\n", "'$version'");	
	}
  else {
  	print $0;
  }
}' < $fn > $tmp

mv $tmp $fn

# Update windows nuspec version.
for fn in ../vs/*.nuspec
do
  awk 'BEGIN{OFS=""}
  {
    idx = index($0,"<version>"); 
    
    if (idx > 0)
    {
      print substr($0, 0, idx+8),"'$version'</version>";
    } 
    else
    {
      print $0
    }
  }' $fn > $fn.tmp

  mv $fn.tmp $fn
done
