#!/bin/bash
# Set version in version.h and version.c.

if [ $# -lt 1 ]
then
	echo "Usage: $0 <version>"
	exit 1
fi

version=$1

cd `dirname $0`

# Write version.h
echo $version | awk -F. '{
	split($3,b,"-");
	printf("// Version format: MNNPPBBBB\n");
	printf("// M: major\n");
	printf("// N: minor\n");
	printf("// P: patch\n");
	printf("// B: build id\n");
	printf("#define AEROSPIKE_CLIENT_VERSION %d%02d%02d%04dL\n", $1, $2, b[1], b[2]);
	printf("\nextern char* aerospike_client_version;\n");
}' > ../src/include/aerospike/version.h

# Write version.c
echo 'char* aerospike_client_version = "'$version'";' > ../src/main/aerospike/version.c

# Update windows nuspec version.
for fn in ../vs/*.nuspec
do
  awk 'BEGIN{OFS=""}
  {
    idx = index($0,"<version>"); 
    
    if (idx > 0)
    {
      print substr($0, 0, idx+8),"'$version'</version>";
    } 
    else
    {
      print $0
    }
  }' $fn > $fn.tmp

  mv $fn.tmp $fn
done
