#!/bin/bash

if [ -n "${RELEASE_VERSION:-}" ]; then
  echo "$RELEASE_VERSION"
  exit 0
fi

rev=`git describe`
subbuild=`echo $rev | awk -F'-' '{print $2}'`

if [ "$subbuild" != "" ]
then
  rev=`echo $rev | awk -F'-' '{printf("%s-%s\n",$1,$2)}'`
fi

echo $rev
