name: Aerospike C Client Tests

on:
  push:
    branches: [master, stage]
  pull_request:
    branches: [master, stage]

permissions:
  id-token: write
  contents: read

jobs:
  builds-on-linux:
    runs-on: ${{ vars.RUNS_ON_LINUX }}
    env:
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
    - name: Checkout client
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Aerospike Database
      uses: aerospike/shared-workflows/.github/actions/setup-aerospike-server@334ad55b790658d549747b0d154407dfc730acca # latest main
      with:
        oidc-provider: ${{ vars.SHAREDWORKFLOW_DB_OIDC_PROVIDER }}
        oidc-audience: ${{ vars.SHAREDWORKFLOW_DB_OIDC_AUDIENCE }}
    - run: ./install_libev
    - run: make EVENT_LIB=libev
    - run: make EVENT_LIB=libev test
    - run: make clean
    - run: ./install_libuv
    - run: make EVENT_LIB=libuv
    - run: make EVENT_LIB=libuv test
    - run: make clean
    - run: ./install_libevent
    - run: make EVENT_LIB=libevent
    - run: make EVENT_LIB=libevent test

  builds-on-mac:
    runs-on: macos-26-intel
    steps:
    - name: Checkout client
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker for macOS
      uses: ./.github/actions/setup-docker-on-macos
    - name: Setup Aerospike Database
      uses: aerospike/shared-workflows/.github/actions/setup-aerospike-server@334ad55b790658d549747b0d154407dfc730acca # latest main
      with:
        oidc-provider: ${{ vars.SHAREDWORKFLOW_DB_OIDC_PROVIDER }}
        oidc-audience: ${{ vars.SHAREDWORKFLOW_DB_OIDC_AUDIENCE }}
    - run: ./install_libev
    - run: make EVENT_LIB=libev
    - run: make EVENT_LIB=libev test
    - run: make clean
    - run: ./install_libuv
    - run: make EVENT_LIB=libuv
    - run: make EVENT_LIB=libuv test
    - run: make clean
    - run: ./install_libevent
    - run: make EVENT_LIB=libevent
    - run: make EVENT_LIB=libevent test

