name: C Client Build & Release

permissions:
  actions: write
  id-token: write
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - CLIENT-4300-release-pipeline-new # keeping for testing sake
      - stage
  workflow_dispatch:

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-artifacts.yml
    with:
      dry-run:        ${{ vars.DRY_RUN_RELEASE == 'true' }} # dry-run would be false by default
      enforce-doxygen-warnings: ${{ vars.ENFORCE_DOXYGEN_WARNINGS != 'false' }} # default on
    secrets: inherit
