name: C Client Build & Release

permissions:
  actions: write
  id-token: write
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - CLIENT-4300-release-pipeline-new
#       # Add long-running release branches here if needed.
#       - stage
   
  #   tags:
  #     - '[0-9]+.[0-9]+.[0-9]+'     # Matches 7.4.0
  #     - '[0-9]+.[0-9]+.[0-9]+-rc*' # Matches 7.4.0-rc1
  workflow_dispatch:

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-artifacts.yml
    with:
      dry-run:        ${{ vars.DRY_RUN_RELEASE == 'true' }}
      check-doc-lint: ${{ vars.CHECK_DOC_LINT != 'false' }} # defaults to true
    secrets: inherit
